EmployeeApp/urls.py
from django.urls import path
from .views import general_views, auth_views

app_name="employee"

urlpatterns = [
    path('', general_views.employee_list, name="index"),
    path('addEmployee', general_views.add_employee, name='addEmployee'),
    path('addExcel', general_views.add_excel, name='addExcel'),
    path('logs', general_views.logs, name='logs'),
    path('logout', auth_views.Logout, name='logout')
]

auth_urlpatterns =[
    path('login', auth_views.login, name='login')    
]

urlpatterns += auth_urlpatterns

InternProject/urls.py
"""InternProject URL Configuration
"""
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('EmployeeApp.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')) #For the the login
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

EmployeeApp/models/employee_model.py
from django.db import models
from EmployeeApp.utils.generate_code import generate_code
# Create your models here.

class Employee(models.Model):
    first_name      = models.CharField(max_length=100)
    middle_name     = models.CharField(max_length=100)
    date_of_graduation= models.DateField(blank=True)
    date_of_employment= models.DateField(blank=True)
    position        = models.CharField(max_length=100)
    salary          = models.IntegerField(default=0)
    supervisors     = models.ManyToManyField('Employee', blank=True)
    employee_code   = models.CharField(max_length=6, blank=True)

    def __str__(self):
        return f'{self.first_name} {self.middle_name}'

    class Meta:
        ordering = ['-id']

        
    def save(self, *args, **kwargs):
        first_name_init = self.first_name[0]
        middle_name_init = self.middle_name[0]
        rand_num         = generate_code()
        code        = first_name_init+middle_name_init+'-'+rand_num
        self.employee_code  = code  
        super().save(*args, **kwargs)

EmployeeApp/models/logs_model.py
from django.db import models

class Log(models.Model):
    STATUS_SUCCESS = "Success"
    STATUS_FAILED  = "Failed"

    StatusChoice = [
        (STATUS_SUCCESS, STATUS_SUCCESS),
        (STATUS_FAILED, STATUS_FAILED)
    ]
    timestamps      = models.DateTimeField(auto_now=True)
    records         = models.IntegerField(default=0)
    status          = models.CharField(max_length=50, choices=StatusChoice)
    errors          = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return 'logs'
    
    class Meta:
        ordering = ['-id']

    

EmployeeApp/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User

from EmployeeApp.models.employee_model import Employee
from EmployeeApp.managers.upload_logs import create_log

class LoginForm(forms.Form):
	username = forms.CharField(max_length=100, required=True,
				widget=forms.TextInput(attrs={
					"placeholder":"Username",
					"id":"username",
					"class":"form-control col-5",
					"placeholder":"Username",
					"autofocus":"" 
				})
				)
	
	password = forms.CharField(max_length=500,
						required=True,
						widget=forms.PasswordInput(attrs={
							"id":"inputPassword", 
							"class":"form-control col-5",
							"placeholder":"Password",
							
						})
						)
	
	class Meta:
		model = User,
		fields = ["username","password"]



class EmployeeForm(ModelForm):
	first_name = forms.CharField(max_length=100, required=True,
				widget=forms.TextInput(attrs={
					"name":"firstName",
					"class":"form-control",
					"id":"firstName"
				})
				)

	middle_name = forms.CharField(max_length=100, required=True,
				widget=forms.TextInput(attrs={
					"name":"middleName",
					"class":"form-control",
					"id":"middleName"
				})
				)

	position = forms.CharField(max_length=100, required=True,
				widget=forms.TextInput(attrs={
					"name":"position",
					"class":"form-control",
					"id":"position"
				})
				)

	salary = forms.CharField(max_length=100, required=True,
				widget=forms.NumberInput(attrs={
					"name":"salary",
					"class":"form-control",
					"id":"salary"
				})
				)


	date_of_employment = forms.CharField(max_length=100, required=True,
				widget=forms.DateInput(attrs={
					"type":"date",
					"name":"dateOfEmployment",
					"class":"form-control",
					"id":"dateOfEmployment"
				})
				)

	date_of_graduation = forms.CharField(max_length=100, required=True,
				widget=forms.DateInput(attrs={
					"type":"date",
					"name":"dateOfGraduation",
					"class":"form-control",
					"id":"dateOfGraduation"
				})
				)
	supervisors = forms.ModelMultipleChoiceField(
		queryset=Employee.objects.all(),
		required=False
		)
	
	class Meta:
		model = Employee
		fields = ["first_name", "middle_name", "position", "salary", "date_of_employment", "date_of_graduation", "supervisors"]

EmployeeApp/views/auth_views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as login_user
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages


from EmployeeApp.forms import LoginForm

# Create your views here.
def login(request):
    form = LoginForm()
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(request,
                        username=form.cleaned_data.get("username"),
                        password=form.cleaned_data.get("password")
                        )
            if user is not None:
                login_user(request, user)
                return redirect('/')
            else:
                messages.error(request, 'Invalid credentials provided. Please note that both fields may be case-sensitive !')

    context={
        "form":form
    }
    return render(request, 'login.html', context)

    


@login_required
def Logout(request):
    logout(request)
    return redirect('/login')

EmployeeApp/views/general_views.py
# Django imports
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import os

# Local app imports 
from EmployeeApp.utils.excel_upload import excel_upload
from EmployeeApp.models.employee_model import Employee
from EmployeeApp.models.logs_model import Log
from EmployeeApp.forms import EmployeeForm
from EmployeeApp.managers.upload_logs import create_log



# Create your views here.
@login_required
def employee_list(request):
	employees = Employee.objects.all()
	context = {
		"employees": employees
	}
	return render(request, 'employee_list.html', context)



@login_required
def add_employee(request):
	form = EmployeeForm()
	if request.method == "POST":
		form = EmployeeForm(request.POST)
		if form.is_valid():
			form.save()
			create_log(
				get_records=1,
			)
			messages.success(request, 'SUCCESSFUL, You added a new Employee !')
		else:
			create_log(
				get_records=0,
				get_errors=messages.error
			)
			messages.error(request, "UNSUCCESSFUL, Couldn't add Employee !")

	context={
		"form":form
	}
	return render(request, 'addEmployee.html', context)



@login_required
def add_excel(request):
	if request.method == "POST":
		excel_file     			= request.FILES.get("employee_excel_file")
		# Getting filename and extension	
		file_name, extension 	= os.path.splitext(excel_file.name)
		if '.xlsx' == extension:
			upload_info = excel_upload(excel_file)
			# Checking if any error occured
			if upload_info[0]==True:
				messages.error(request, upload_info[1])

			# Valid file
			else:
				messages.success(request, "Employee Data uploaded successfully")
						
		# If file wasn't a '.xlsx'
		else:
			messages.error(request, "Invalid file upload, please upload an excel file")
			
	return render(request, 'addExcel.html')




@login_required
def logs(request):
	logs = Log.objects.all()
	context={
		"logs":logs
	}
	return render(request, 'logs.html', context)

EmployeeApp/templates/addEmployee.html
{% include 'head.html' %}

<div class="container">
  {% include 'header.html' %}

  <form method="POST" class="p-2 shadow mb-5">
    {% csrf_token %}
    <fieldset>
      <legend><h1>Add New Member</h1></legend>
      {% if forms.errors %} {% for key, value in forms.errors.items %}
      <b>{{ value }}</b>
      {% endfor %} {% endif %} {% if messages %} {% for message in messages %}
      <div class="alert alert-danger alert-dismissible" role="alert">
        <div id="form-errors">
          <strong>{{ message }}</strong>
        </div>
      </div>
      {% endfor %} {% endif %}

      <div class="form-row row">
        <div class="col-sm-5 mb-3 form-group">
          <label for="firstName" class="form-label">First Name</label>
          <!--<input type="text" name="firstName" class="form-control" id="firstName">-->
          {{form.first_name}}
        </div>

        <div class="col-sm-5 mb-3 form-group">
          <label for="middleName" class="form-label">Middle Name</label>
          <!--<input type="text" name="middleName" class="form-control" id="middleName">-->
          {{form.middle_name}}
        </div>

        <div class="col-sm-5 mb-3 form-group">
          <label for="position" class="form-label">Position</label>
          <!--<input type="text" name="position" class="form-control" id="position">-->
          {{form.position}}
        </div>

        <div class="col-sm-5 mb-3 form-group">
          <label for="salary" class="form-label">Salary (US $)</label>
          <!--<input type="number" min='0' max='5000' name="salary" class="form-control" id="salary">-->
          {{form.salary}}
        </div>

        <div class="col-sm-5 mb-3 form-group">
          <label for="dateOfEmployment" class="form-label"
            >Date of Employment</label
          >
          <!--<input type="date" name="dateOfEmployment" class="form-control" id="dateOfEmployment">-->
          {{form.date_of_employment}}
        </div>

        <div class="col-sm-5 mb-3 form-group">
          <label for="dateOfGraduation" class="form-label"
            >Date of Graduation</label
          >
          <!--<input type="date" name="dateOfGraduation" class="form-control" id="dateOfGraduation">-->
          {{form.date_of_graduation}}
        </div>

        <div class="col-sm-5 mb-3 form-group">
          <label for="employeeSupervisor" class="form-label"
            >Choose a Supervisor</label
          >
          {{form.supervisors}}
        </div>
      </div>
    </fieldset>
    <input type="submit" value="Add" class="btn btn-primary col-3" />
  </form>
</div>

EmployeeApp/templates/addExcel.html
{% include 'head.html' %}

<div class='container'>
    {% include 'header.html' %}

    <form method="POST" class="p-2 shadow mb-5"  enctype="multipart/form-data">
        {% csrf_token %}

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <div id="form-errors">
                        <strong>{{ message }}</strong>
                    </div>
                </div>
            {% endfor %}
        {% endif %}

        <fieldset>
            <legend><h1>Add Excel File</h1></legend>
            {% if error_message %}<p class="text-danger"><b>{{ error_message }}</b></p> {% endif %}
            <div class="form-row row">
                <div class="col-sm-5 mb-3 form-group">
                    <label for="addExcel" class="form-label">Choose an Excel File</label>
                    <input type="file" name="employee_excel_file" class="form-control" id="addExcel">
                </div>
            </div>
        </fieldset>

        <input type="submit" value="Add" class="btn btn-primary col-3">
    </form>
</div>

EmployeeApp/templates/employee_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>EmployeeApp</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    
</head>



<body class="container-fluid">
  <div class="container">{% include 'header.html'%}</div>
  <main>
    
    <h1>All Employee</h1><br>
    <div class="row">

      <table class="table shadow">
        <thead>
          <tr>
            <th scope="col">First Name</th>
            <th scope="col">Middle Name</th>
            <th scope="col">Position</th>
            <th scope="col">Salary($)</th>
            <th scope="col">Supervisors</th>
            <th scope="col">Date of Employment</th>
            <th scope="col">Date of Graduation</th>
            <th scope="col">Code</th>
          </tr>
        </thead>
        <tbody>
        {% for employee in employees %}
      
          <tr>
            <td>{{employee.first_name}}</td>
            <td>{{employee.middle_name}}</td>
            <td>{{employee.position}}</td>
            <td>{{employee.salary}}</td>
            <td>
              <i>
                {% for supervisor in employee.supervisors.all %}
                    {{supervisor}},<br>
                  {% empty %}
                  None
                {% endfor %}
              </i>
            </td>
            <td>{{employee.date_of_employment}}</td>
            <td>{{employee.date_of_graduation}}</td>
            <td>{{employee.employee_code}}</td>
          </tr>
          
        {% endfor %}
        </tbody>
      </table>

    
      {% comment %} <div class="col-sm-6 mb-4">
        <div class="card shadow">
          <div class="card-body">
            <h4 class="card-title">{{employee.first_name}} {{employee.middle_name}}</h4>
            <h6 class='card-text'>({{ employee.position }}) --- [ {{ employee.employee_code }} ]</h6>
            <a href="#" class="btn btn-success p-2">Salary: $ {{ employee.salary }}</a><br><br>
    
            <i>
              
              Supervisor(s): 
                {% for supervisor in employee.supervisors.all %}
                  {{supervisor}}
                {% empty %}
                None
                {% endfor %}
              
            </i>
            <br><br>
            <z class="card-text">--<b>Date of Employment</b>-- {{ employee.date_of_employment }}</z><br>
            <z class="card-text">--<b>Date of Graduation</b>-- {{ employee.date_of_graduation }}</z>
    
          </div>
        </div>
      </div>
    {% endfor %} {% endcomment %}
        
    
    
    </div>
  </main>
  <!-- <script>
    document.querySelector('#img').addEventListener('click',()=>alert('What the fuck'))
  </script> -->
</body>
</html>

EmployeeApp/templates/head.html
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>EmployeeApp</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>

EmployeeApp/templates/header.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EmployeeApp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</head>



<body class="container">
    <!-- Nav section -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand text-primary shadow p-2" href="{% url 'employee:index' %}">Employee Management System </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-5">

                <li class="nav-item">
                <a class="nav-link" href="{% url 'employee:index' %}">List of Employees</a>
                </li>

                <li class="nav-item">
                <a class="nav-link" href="{% url 'employee:addEmployee' %}">Add Employer Manually</a>
                </li>

                <li class="nav-item">
                <a class="nav-link" href="{% url 'employee:addExcel' %}">Add Excel File</a>
                </li>

                <li class="nav-item">
                <a class="nav-link" href="{% url 'employee:logs' %}">Logs / List</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-danger" href="{% url 'employee:logout' %}">Logout</a>
                </li>


            </ul>
            </div>
        </div>
    </nav><br><br>
</body>

EmployeeApp/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EmployeeApp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</head>



<body class="text-center container">
    {% include 'header.html' %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger alert-dismissible" role="alert">
        <div id="form-errors">
            <strong>{{ message }}</strong>
        </div>
        
    </div>
    {% endfor %}
    {% endif %}
    {% if forms.errors %}
        {% for key, value in forms.errors.items %}
            <b>{{ value }}</b>
        {% endfor %}
    {% endif %}
    <div class="container m-auto">
        <br>
        <h1 class="mb-3 font-weight-normal text-primary">Login</h1>
        <br>
        <form method='POST' class="form-signin col-6 m-auto">
            {% csrf_token %}
                

                <div class="form-group">
                    <label for="username" class="sr-only "><h4>Username</h4></label>
                    {{form.username}}
                    <br>
                </div>

                <div class="form-group">
                    <label for="inputPassword" class="sr-only"><h4>Password</h4></label>
                    {{form.password}}
                    <br>
                </div>

                <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>

                </div>
        </form>
    </div>
    

</body>

</html>

EmployeeApp/templates/logs.html
{% include 'head.html' %}

<div class='container'>
    {% include 'header.html' %}

    {% comment %} For the number of Logs , display in a table here {% endcomment %}
    <table class="table container-fluid">
        <legend><h1>Logs of Uploads</h1></legend><br>
    <thead>
        <tr>
        <th scope="col">Timestamp</th>
        <th scope="col">Employee records</th>
        <th scope="col">Status</th>
        <th scope="col">Errors</th>
        </tr>
    </thead>
    <tbody>
        <!-- Record starts here-->
        {% for log in logs %}
            <tr>
            <td scope="row">{{ log.timestamps.date}}<br> {{ log.timestamps.time}}</td>
            <td >{{ log.records }}</td>
            <td>{{ log.status }}</td>
            <td>
                {% if log.errors %}
                    {{log.errors}}
                {% else %}
                    ---
                {% endif %}

            </td>
            </tr>
            {% empty %}
                <td><h3 class="text-danger">No Logs</h3></td>
        {% endfor %}
        <!-- ends here -->

    </tbody>
    </table>
</div>